security:
    # https://symfony.com/doc/current/security.html#c-hashing-passwords
    password_hashers:
        App\Entity\User: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: email

        jwt:
            lexik_jwt:
                class: App\Component\User\Dtos\JwtUserDto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/(login_check|users)
            stateless: true
            security: false

        main:
            pattern: ^/api
            stateless: true
            provider: entity_provider
            jwt: ~

    access_control:
#         PUBLIC routes for anonymous users
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
        - { path: ^/api/users, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/upload, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/results/, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/feedback_results/, roles: PUBLIC_ACCESS, methods: [GET] }
#         To Allow Swagger
        - { path: ^/api, roles: PUBLIC_ACCESS, methods: [GET] }

#            SECURE routes for logged-in users
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
